name: "Integration Test"

on: [push, pull_request]

jobs:
  integration_test:
    name: "Integration Test"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Integration Test
      env:
        STORAGE_STORJ_INTEGRATION_TEST: "on"
        STORAGE_STORJ_CREDENTIAL: "apikey:${{ secrets.STORJ_CREDENTIAL }}"
        STORAGE_STORJ_NAME: "gostorage"
      run: make integration_test
